spring:
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
logging:
  level:
    ROOT: info
